"""
Publication figure combining selected environmental forcing with plant- and
fruit-level model output under a simulated 8-day storm scenario and default
conditions. Panels (a) and (b) show incoming radiation and prescribed soil
water potential; panels (c)--(j) show the eight retained model responses. The
complete five-panel forcing figure is generated by plot_model_output_3_new.py.

Framing (for caption/methods): this storm event is a SYNTHETIC test case,
not a validated/observed weather event. Its purpose is to demonstrate the
coupled response to compound atmospheric forcing and rapid soil wetting
followed by drainage -- not to represent a specific real storm. The prescribed
soil water potential crosses the configured wet-side threshold and reaches the
zero-uptake boundary for 18 hourly records. This exercises the model's
empirical waterlogging limiter, but it is not a mechanistic representation of
root-zone oxygen stress.

Caption note: water flux is a plant-level total reported per simulated vine.
Mean fruit fresh mass, dry mass and sugar concentration are read from the mean-fruit output
table.

Units are taken from the forcing columns and the plant-level and mean-fruit
metadata. The common time axis is anchored to the configured simulation start
(day 200, hour 0). Model output begins at hour 1, while forcing begins at hour
0; neither series is shifted to conceal that difference.

OPEN QUESTIONS FOR LEAD AUTHOR:
  - Confirm whether single deterministic runs are sufficient for
    publication, or whether replicate runs + uncertainty bands are
    expected.
  - The two plotted scenarios use the common-pool carbon option
    (`useCTRAM=false`), for which the active model definition is g sugar per
    g solution. The generic metadata unit is mode-independent and is not used
    for this panel label.
  - `fraction_fruitUnloading` has no unit listed in the metadata (assumed
    unitless, 0-1 fraction) -- confirm.

Usage:
    python plot_model_output_4_new.py
Requires: pandas, matplotlib, numpy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from pathlib import Path

# ---------------------------------------------------------------------------
# Publication-style formatting
# ---------------------------------------------------------------------------
mpl.rcParams.update({
    "font.family": "serif",
    "font.size": 13,
    "axes.labelsize": 13,
    "axes.titlesize": 13,
    "legend.fontsize": 11,
    "xtick.labelsize": 11,
    "ytick.labelsize": 11,
    "axes.linewidth": 0.8,
    "figure.dpi": 300,
})

# Okabe-Ito colorblind-safe palette
COLOR_DRY = "#D55E00"      # vermillion
COLOR_DEFAULT = "#0072B2"  # blue
COLOR_SAT = "#009E73"      # green

# Shared with plot_storm_3_new.py so phase boundaries and shading match.
PHASES = [
    (0, 72, "Approach", "#f5f0c8"),
    (72, 144, "Heavy rain", "#dbe6f2"),
    (144, 192, "Clearing", "#dcf2df"),
]
PHASE_ALPHA = 0.4

# ---------------------------------------------------------------------------
# Load scenario outputs
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
BASE = SCRIPT_DIR

df = pd.read_csv(BASE / "DAI_2012_12L_stormPub/plant-level-DAI_2012_12L_stormPub.csv")
df_1 = pd.read_csv(BASE / "DAI_2012_12L_storm_default/plant-level-DAI_2012_12L_storm_default.csv")
df_fruit = pd.read_csv(BASE / "DAI_2012_12L_stormPub/mean-fruit-DAI_2012_12L_stormPub.csv")
df_1_fruit = pd.read_csv(BASE / "DAI_2012_12L_storm_default/mean-fruit-DAI_2012_12L_storm_default.csv")

# ---------------------------------------------------------------------------
# Common time axis. Plant/fruit output uses dayOfYear and hourOfDay, whereas
# forcing uses day and hour. All are converted to hours since the configured
# start. Plant output begins one hour later and is therefore plotted from t=1.
# ---------------------------------------------------------------------------
def abs_hours(data):
    return data["dayOfYear"] * 24 + data["hourOfDay"]

SIM_START_DAY, SIM_START_HOUR = 200, 0
T0 = SIM_START_DAY * 24 + SIM_START_HOUR

def hours_axis(data):
    return abs_hours(data) - T0

def load_forcing(path):
    data = pd.read_csv(path)
    data["hours"] = data["day"] * 24 + data["hour"] - T0
    return data[(data["hours"] >= 0) & (data["hours"] <= 192)].sort_values("hours")

df_forcing = load_forcing(
    BASE / "DAI_2012_12L_stormPub/run-config/Exp2012_Dai_Bordeaux_climateConditionsAfterVeraison-STORM.csv"
)
df_1_forcing = load_forcing(
    BASE / "DAI_2012_12L_storm_default/run-config/Exp2012_Dai_Bordeaux_climateConditionsAfterVeraison_storm_default.csv"
)

scenarios = [
    {
        "forcing": df_forcing,
        "plant": df,
        "fruit": df_fruit,
        "label": "Storm (dry-to-wet)",
        "color": COLOR_DRY,
    },
    {
        "forcing": df_1_forcing,
        "plant": df_1,
        "fruit": df_1_fruit,
        "label": "Default conditions",
        "color": COLOR_DEFAULT,
    },
]

# ---------------------------------------------------------------------------
# Variables to plot: (output level, column, panel label, title, y-axis label)
# Units taken from plant-level.metadata.json and mean-fruit.metadata.json.
# ---------------------------------------------------------------------------
variables = [
    ("forcing", "totalRadiation", "a", "Incoming total radiation", r"Radiation ($\mu$mol m$^{-2}$ s$^{-1}$)"),
    ("forcing", "soilWater_Potential", "b", "Soil water potential", r"$\psi_{\mathrm{soil}}$ (MPa)"),
    ("plant", "meanAnet", "c", "Mean net photosynthesis", r"$A_{\mathrm{net}}$ ($\mu$mol CO$_2$ m$^{-2}$ s$^{-1}$)"),
    ("plant", "waterFlux_optimized", "d", "Instantaneous water flux", r"Water flux (mg vine$^{-1}$ s$^{-1}$)"),
    ("plant", "xylemWaterPotential", "e", "PlantBase xylem water potential", r"$\psi_{\mathrm{xylem}}$ (MPa)"),
    ("plant", "phloemSugarConcentration", "f", "Common-pool sugar mass fraction", r"$C_{\mathrm{pool}}$ (g sugar g$^{-1}$ phloem sap)"),
    ("plant", "fraction_fruitUnloading", "g", "Fruit unloading fraction", r"Unloading fraction ($-$)"),
    ("fruit", "meanFruitSc", "h", "Mean fruit sugar concentration", r"$\overline{C}_{\mathrm{fruit}}$ (g g$^{-1}$ water)"),
    ("fruit", "meanFruitFW", "i", "Mean fruit fresh mass", r"Fresh mass (mg)"),
    ("fruit", "meanFruitDW", "j", "Mean fruit dry mass", r"Dry mass (mg)"),
]

# ---------------------------------------------------------------------------
# Build the subplot grid
# ---------------------------------------------------------------------------
ncols = 2
nrows = -(-len(variables) // ncols)  # ceil division
fig, axes = plt.subplots(nrows, ncols, figsize=(10, 3.1 * nrows), sharex=True)
axes = axes.flatten()

for ax, (output_level, col, panel_label, title, ylabel) in zip(axes, variables):
    # Draw the default first and the storm last so overlapping storm values
    # remain visible. Legend order is set independently below.
    for scenario in reversed(scenarios):
        data = scenario[output_level]
        label = scenario["label"]
        color = scenario["color"]
        t = data["hours"] if output_level == "forcing" else hours_axis(data)
        zorder = 3 if label == "Storm (dry-to-wet)" else 2
        ax.plot(t, data[col], label=label, color=color, linewidth=1.1,
                zorder=zorder)
    for start_h, end_h, _, shade in PHASES:
        ax.axvspan(start_h, end_h, color=shade, alpha=PHASE_ALPHA, zorder=0)
    ax.set_title(f"({panel_label}) {title}", loc="left", fontweight="bold", pad=8)
    ax.set_ylabel(ylabel)
    ax.set_xlim(0, 192)
    ax.set_xticks(np.arange(0, 193, 24))
    ax.grid(alpha=0.25, linewidth=0.5)

for ax in axes[-ncols:]:
    ax.set_xlabel("Time since simulation start (h)")

# Reserve fixed space below the grid for the shared legend.
fig.tight_layout(rect=[0, 0.07, 1, 1])

# Single shared legend, retaining the requested storm/default display order.
plotted_handles, plotted_labels = axes[0].get_legend_handles_labels()
handle_by_label = dict(zip(plotted_labels, plotted_handles))
labels = [scenario["label"] for scenario in scenarios]
handles = [handle_by_label[label] for label in labels]
fig.legend(
    handles,
    labels,
    loc="lower center",
    ncol=len(scenarios),
    bbox_to_anchor=(0.5, 0.025),
    frameon=False,
)

# Hide unused axes if variables doesn't evenly fill the grid
for ax in axes[len(variables):]:
    ax.axis("off")

for stem in ("storm_combined_10panel", "model_output_summary"):
    fig.savefig(SCRIPT_DIR / f"{stem}.png", dpi=300, bbox_inches="tight")
    fig.savefig(SCRIPT_DIR / f"{stem}.pdf", bbox_inches="tight")
plt.close(fig)
