name: Build FruitCropXL Documentation

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Doxygen and Graphviz
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -yq update
          sudo apt-get -yq install doxygen graphviz

      - name: Build documentation
        run: bash Model_documents/FruitCropXL_doc_bash/module_replace.sh

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: Model_documents/FruitCropXL_doc
          clean: true
